### ISSUE TITLE
Is there a queue runner to start training?

### ISSUE THREAD

**Issue by mingxuan-yi** [takerum/vat_tf#1]
Hi, I have reviewed your codes for vat. One thing I am confused is that how do you run the training graph? I saw the inputs are read from tfrecords, there are a coordinator and tf. start_queue_runner in test.py, but I did not find anything like that in train_semisup.py.

**Comment by takerum** [comment]
Hi, thanks for your attention!

In train_semisup.py, I used ```sv = tf.train.Supervisor``` in https://github.com/takerum/vat_tf/blob/master/train_semisup.py#L146, which is a training helper for automatically saving checkpoints and summaries, and ```tf.start_queue_runners()``` is automatically called in ```sv.managed_session()``` in https://github.com/takerum/vat_tf/blob/master/train_semisup.py#L158.

Please see below source for the details.
https://github.com/tensorflow/tensorflow/blob/a462e0f1911ecbf0650faf5ef7ec543801848c54/tensorflow/python/training/supervisor.py#L717

**Comment by mingxuan-yi** [comment]
Thanks very much.
