### ISSUE TITLE
What are vat.xi and vat.eplison optimal values?.

### ISSUE THREAD

**Issue by bbdamodaran** [takerum/vat_tf#13]
In your implementation vat.xi = 1e-6, and when you do
vat.xi * d # is the random unit vector
It is close to zero right?, whether vat.xi should be greater than 1.

I am confused between vat.xi and vat.eplison ? can you clarify this

thanks in advance

**Comment by takerum** [comment]
Please see Section 3.3 in this paper: https://arxiv.org/pdf/1704.03976.pdf.
xi is used for the approximation of Hessian-vector product while the epsilon is the norm constraint of the adversarial perturbation.

**Comment by bbdamodaran** [comment]
thanks.. Now I understood, that vat.xi is 1e-6 for the finite difference method.
