### ISSUE TITLE
is_training = True

### ISSUE THREAD

**Issue by yqweixiang** [takerum/vat_tf#4]
Hi,

Thanks for this excellent algorithm and accompanying code.
After reading your code, I found one issue, that is in your train_semisup.py file of line 86. Why you set the is_training as true when you do your evaluation? Will that influence the final result? What if I change it to false?

Best,
Xiang

**Comment by takerum** [comment]
Thank you for the comment!, it's my mistake and it should be that is_training = False on the evaluation of the virtual adversarial loss. I fixed the code, but the final result should not be influenced by this change.

**Comment by yqweixiang** [comment]
@takerum Thanks for the reply, I'm running the code with is_training set to True and False. However, so far, it seems that it will influence the training process. I will check the results in the following days. Thanks!

**Comment by takerum** [comment]
I see, but the flags on evaluation affects only on its value, and does not affect on the learning parameters. Therefore, the learned model is not be changed by changing the flags on evaluation, while the printed values at each evaluation may be changed.

**Comment by yqweixiang** [comment]
@takerum As I see, some of the training_loss on "False" are different from the "True", I think if you set the is_training to true, the test data will train the model for every 5 epochs as you will evaluate the model for every 5 epochs with testing data. I will check the results in the following days, and you may want to double check that.
